name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ '1.14', '1.15', '1.16', '1.17' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -race -tags '${{ matrix.tags }}' -v ./...
        if: runner.os != 'Windows'
      - name: Test (without race detector)
        run: go test -tags '${{ matrix.tags }}' -v ./...
        if: runner.os == 'Windows'